#include "mbed.h"

PinName DIGIT1_PINA = B12;
PinName DIGIT1_PINB = B13;
PinName DIGIT1_PINC = B14;
PinName DIGIT1_PIND = B15;

PinName DIGIT2_PINA = A8;
PinName DIGIT2_PINB = A9;
PinName DIGIT2_PINC = A10;
PinName DIGIT2_PIND = A11;

PinName DIGIT3_PINA = A12;
PinName DIGIT3_PINB = A15;
PinName DIGIT3_PINC = B3;
PinName DIGIT3_PIND = B4;

PinName DIGIT4_PINA = B6;
PinName DIGIT4_PINB = B7;
PinName DIGIT4_PINC = B8;
PinName DIGIT4_PIND = B9;

PinName HOUR_BUTTON_PIN = A1;
PinName MINUTE_BUTTON_PIN = A0;

PinName statusLed = LED1;